spring.application.name=bank_microservice
server.port=7070
spring.datasource.url=jdbc:postgresql://localhost:5435/finance_software_db
#if needed change the username
spring.datasource.username=postgres
# create the DB (inside database folder) and then change the password to your name
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.user.name=dima
spring.security.user.password=dima


spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

